executor: slurm
software-deployment-method:
  - conda
conda-prefix: .conda

jobs: 40
max-jobs-per-second: 5

slurm-efficiency-report: true
slurm-efficiency-report-path: logs/efficiency
slurm-efficiency-threshold: 0.8

default-resources:
  slurm_account: genomeatlas_umassmed
  slurm_partition: cpu
  runtime: 60m
  mem_mb: 4000

set-threads:
  macs3: 1
  bam2bw: 4
  negatives: 1
  fit: 4
  evaluate: 4

set-resources:
  macs3:
    mem_mb: max(8000, 5 * input.size_mb) * attempt
    runtime: min(1440, max(60, 0.05 * input.size_mb) * attempt)
  bam2bw:
    mem_mb: 16000 * attempt
    runtime: min(1440, 480 * attempt)
  negatives:
    mem_mb: 8000 * attempt
    runtime: 60m
  fit:
    slurm_partition: b200-batch
    gres: gpu:1
    mem_mb: 32000 * attempt
    runtime: 240m
  evaluate:
    slurm_partition: b200-batch
    gres: gpu:1
    mem_mb: 24000 * attempt
    runtime: 120m

rerun-incomplete: true
keep-going: true
show-failed-logs: true
benchmark-extended: true
retries: 1
slurm-requeue: false
printshellcmds: true
latency-wait: 60
